const keys = [
  { code: 'Backquote', ru: 'ё', en: '`' },
  { code: 'Digit1', ru: '1', en: '1' },
  { code: 'Digit2', ru: '2', en: '2' },
  { code: 'Digit3', ru: '3', en: '3' },
  { code: 'Digit4', ru: '4', en: '4' },
  { code: 'Digit5', ru: '5', en: '5' },
  { code: 'Digit6', ru: '6', en: '6' },
  { code: 'Digit7', ru: '7', en: '7' },
  { code: 'Digit8', ru: '8', en: '8' },
  { code: 'Digit9', ru: '9', en: '9' },
  { code: 'Digit0', ru: '0', en: '0' },
  { code: 'Minus', ru: '-', en: '-' },
  { code: 'Equal', ru: '=', en: '=' },
  { code: 'Backspace', ru: 'backspace', en: 'backspace' },
  { code: 'Tab', ru: 'tab', en: 'tab' },
  { code: 'KeyQ', ru: 'й', en: 'q' },
  { code: 'KeyW', ru: 'ц', en: 'w' },
  { code: 'KeyE', ru: 'у', en: 'e' },
  { code: 'KeyR', ru: 'к', en: 'r' },
  { code: 'KeyT', ru: 'е', en: 't' },
  { code: 'KeyY', ru: 'н', en: 'y' },
  { code: 'KeyU', ru: 'г', en: 'u' },
  { code: 'KeyI', ru: 'ш', en: 'i' },
  { code: 'KeyO', ru: 'щ', en: 'o' },
  { code: 'KeyP', ru: 'з', en: 'p' },
  { code: 'BracketLeft', ru: 'х', en: '[' },
  { code: 'BracketRight', ru: 'ъ', en: ']' },
  { code: 'Backslash', ru: '\\', en: '\\' },
  { code: 'Del', ru: 'del', en: 'del' },
  { code: 'CapsLock', ru: 'caps lock', en: 'caps lock' },
  { code: 'KeyA', ru: 'ф', en: 'a' },
  { code: 'KeyS', ru: 'ы', en: 's' },
  { code: 'KeyD', ru: 'в', en: 'd' },
  { code: 'KeyF', ru: 'а', en: 'f' },
  { code: 'KeyG', ru: 'п', en: 'g' },
  { code: 'KeyH', ru: 'р', en: 'h' },
  { code: 'KeyJ', ru: 'о', en: 'j' },
  { code: 'KeyK', ru: 'л', en: 'k' },
  { code: 'KeyL', ru: 'д', en: 'l' },
  { code: 'Semicolon', ru: 'ж', en: ';' },
  { code: 'Quote', ru: 'э', en: '"' },
  { code: 'Enter', ru: 'enter', en: 'enter' },
  { code: 'ShiftLeft', ru: 'shift', en: 'shift' },
  { code: 'KeyZ', ru: 'я', en: 'z' },
  { code: 'KeyX', ru: 'ч', en: 'x' },
  { code: 'KeyC', ru: 'с', en: 'c' },
  { code: 'KeyV', ru: 'м', en: 'v' },
  { code: 'KeyB', ru: 'и', en: 'b' },
  { code: 'KeyN', ru: 'т', en: 'n' },
  { code: 'KeyM', ru: 'ь', en: 'm' },
  { code: 'Comma', ru: 'б', en: ',' },
  { code: 'Dot', ru: 'ю', en: '.' },
  { code: 'Slash', ru: '.', en: '/' },
  { code: 'ArrowUp', ru: '↑', en: '↑' },
  { code: 'ShiftRight', ru: 'shift', en: 'shift' },
  { code: 'ControlLeft', ru: 'ctrl', en: 'ctrl' },
  { code: 'Win', ru: 'win', en: 'win' },
  { code: 'AltLeft', ru: 'alt', en: 'alt' },
  { code: 'Space', ru: ' ', en: ' ' },
  { code: 'AltRight', ru: 'alt', en: 'alt' },
  { code: 'ArrowLeft', ru: '←', en: '←' },
  { code: 'ArrowDown', ru: '↓', en: '↓' },
  { code: 'ArrowRight', ru: '→', en: '→' },
  { code: 'ControlRight', ru: 'ctrl', en: 'ctrl' },
];


export default keys;
